networks:
  traefik-net:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aredutainment-app
    restart: always
    working_dir: /var/www/html
    expose:
      - "80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db-aredutainment
      DB_PORT: 3306
      DB_DATABASE: aredutainment
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      CACHE_DRIVER: file
      QUEUE_DRIVER: database
    networks:
      - traefik-net
    depends_on:
      db-aredutainment:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aredutainment.rule=Host(`aredutainment.okfn.gr`)" # Change to your domain
      - "traefik.http.routers.aredutainment.entrypoints=websecure"
      - "traefik.http.routers.aredutainment.tls=true"
      - "traefik.http.services.aredutainment.loadbalancer.server.port=80"
  db-aredutainment:
    image: mysql:8.0
    container_name: aredutainment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aredutainment
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - traefik-net
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
        interval: 10s
        retries: 5
volumes:
  db_data:
